### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by rebeccaringuette**
Lutz, Shawn and I (Rebecca) had to comment these two lines out to get the kamodo_ccmc imports to work.

### CODE REVIEW

**Comment by asher-pembroke** [comment]
This is not necessary - the problem is that readers were not picked up by the MANIFEST.in
I'll create a separate pull request to that effect.

**Comment by darrendezeeuw** [comment]
I'll hold on to this for now. I've added Asher's pull request we can test to see if this is still needed..

**Comment by rebeccaringuette** [comment]
I'll test this shortly.

Rebecca Ringuette

**Comment by rebeccaringuette** [comment]
Asher's change works. I can now install kamodo correctly without the -e option.

**Pull request closed without merging**
